### ISSUE TITLE
Sender certificate is self-issued on each message to a public endpoint

### ISSUE THREAD

**Issue by gnarea** [relaycorp/awala-endpoint-android#14]
https://github.com/relaycorp/relaynet-endpoint-android/pull/13/files#diff-e0c7ccb83d5575f79a81657ef17c3cdda1157d5d47bdf559fb4d4e701a493a1dR65-R72

This is an expensive operation, so we should ideally cache it on disk and issue a new one iff the cached one will expire in the next `X` days. Where `X` is TBD, but probably between 90 and 120.

**Comment by gnarea** [comment]
I suspect this may have been fixed by chance with the implementation of the certificate renewal.

**Comment by Filmaluco** [comment]
@gnarea o.O 
guess we can close this issue then?

**Comment by gnarea** [comment]
I've just checked and we're indeed caching it in the certificate store ✔️
