### ISSUE TITLE
Re-register first-party endpoints when the private gateway's certificate changes

### ISSUE THREAD

**Issue by gnarea** [relaycorp/awala-endpoint-android#175]
# What to do with old certificates

Old certificates should continue to be used in all calls to `parcel.validate()`. The old (yet valid) certificates should be passed as `trustedCertificates`, along with the new certificate.

Old certificates should only be deleted after they expire (e,g., once a day, when the app starts). However, expired certificates must not be included in the `trustedCertificates` above.

# What to do with the new certificate

The new certificate should be used in all calls to `parcel.serialize()` and `issueDeliveryAuthorization()`. This shouldn't require code any further code changes, but I'm documenting this requirement to make sure we don't change the code inadvertently.

# Related issues

- https://github.com/relaycorp/relaynet-gateway-android/issues/539

**Comment by sdsantos** [comment]
- [ ] Use all valid 1st party certificates to validate incoming messages, instead of just the latest (ReceiveMessages#getNonceSigners)
- [ ] Delete expired 1st party certificates on library setup, in the background (Awala#setUp)
