### ISSUE TITLE
Fix flaky test in PublicThirdPartyEndpointTest

### ISSUE THREAD

**Issue by gnarea** [relaycorp/awala-endpoint-android#200]
As discussed in https://github.com/relaycorp/awala-endpoint-android/pull/199#issuecomment-1062777602, the following test is flaky:

https://github.com/relaycorp/awala-endpoint-android/blob/9eafe5fb41ee1baffd19502923cac64ea2bff702/lib/src/test/java/tech/relaycorp/awaladroid/endpoint/PublicThirdPartyEndpointTest.kt#L64

Here's the error we got in https://github.com/relaycorp/awala-endpoint-android/runs/5411900091?check_suite_focus=true:

```
> Task :lib:testReleaseUnitTest

tech.relaycorp.awaladroid.endpoint.PublicThirdPartyEndpointTest > import_validConnectionParams FAILED
    java.lang.IllegalArgumentException at PublicThirdPartyEndpointTest.kt:64

84 tests completed, 1 failed
```

**Comment by Filmaluco** [comment]
@gnarea has this one happened again, can't find a recent one? 
with IllegalArgumentException I can't seem to understand what went wrong... or what to attempt to do... 
Adding an entery dependency like barista just to allow a flaky test seems overkill.

**Comment by gnarea** [comment]
@Filmaluco, indeed, it's been such a long time since the last time it happened that GitHub already deleted the respective CI logs. I'm going to close this and we can reopen it if it happens again.

I did come across another flaky test as reported on #273. Can you please look into that one instead, since the logs are still available and we have the Gradle build scan.
