### ISSUE TITLE
Fix flaky test AwalaTest.deleteExpiredOnSetUp

### ISSUE THREAD

**Issue by gnarea** [relaycorp/awala-endpoint-android#273]
```
tech.relaycorp.awaladroid.AwalaTest > deleteExpiredOnSetUp FAILED
    java.lang.AssertionError at AwalaTest.kt:87
```

https://github.com/relaycorp/awala-endpoint-android/actions/runs/2971016223/jobs/4757781102

https://scans.gradle.com/s/2mfrpujkqar7u/tests/:lib:testDebugUnitTest/tech.relaycorp.awaladroid.AwalaTest/deleteExpiredOnSetUp?top-execution=1

**Comment by gnarea** [comment]
BTW, this happened in #265, so it may or may not be a regression introduced in that PR.

**Comment by Filmaluco** [comment]
Fixed with https://github.com/relaycorp/awala-endpoint-android/pull/265
