### ISSUE TITLE
Upgrade JaCoCo when Android Gradle Plugin 4.2 is released

### ISSUE THREAD

**Issue by gnarea** [relaycorp/awala-endpoint-android#6]
[We're pinning an old version of JaCoCo](https://github.com/relaycorp/relaynet-endpoint-android/pull/3/files#diff-8c83c59a56db1a4c393645d215c8abae1448a0d5be9e2897f73e06c23e63c0f5R4-R5) because of a bug in the [Android Gradle Plugin](https://issuetracker.google.com/issues/178015739) that's been fixed and will be available in the upcoming 4.2 release.

**Comment by Filmaluco** [comment]
@gnarea I believe this one can also be closed.
https://github.com/relaycorp/awala-endpoint-android/pull/274

Dependabot already must have made the upgrade, because on that PR it's using the latest version

**Comment by gnarea** [comment]
Thanks for looking into this, @Filmaluco!

Dependabot can't manage JaCoCo because it isn't managed as an actual Gradle dependency. See `jacoco.gradle`.

However, I just checked and you already upgraded it to the latest version in #235, so I'm closing this issue.
